### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by GreatAlexander** [assistive-autonomy/baxter_tower#1]
ESSENTIAL:
- [x] Implement multiple above-table poses to search for cubes
- [ ] Implement many many thresholded waits and recoveries
- [x] Face expressions and other feedback

OPTIONAL:
- [ ] Use IR to measure tower height, instead of relying on number of placed cubes

DEMO DAY:
- [ ] Delimit Baxter workspace (Draw on table cube space)
- [ ] Physically constrain Baxter's safe workspace (Check angles before sending them)

**Comment by heramb-modugula** [comment]
[insert SpongeBob timecard]
10 YEARS LATER

Face expressions have finally been added!
